# Generated by Django 2.2 on 2019-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_databases', '0002_remove_englishwordmodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishwordmodel',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
