# Generated by Django 2.2 on 2019-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_databases', '0005_strengthenmemorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishwordrecordmodel',
            name='memory_power',
            field=models.IntegerField(default=1, help_text='记忆力持久度'),
        ),
        migrations.AddField(
            model_name='strengthenmemorymodel',
            name='memory_power',
            field=models.IntegerField(default=1, help_text='记忆力持久度'),
        ),
    ]
