# Generated by Django 2.2 on 2019-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_databases', '0007_auto_20190415_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='level',
            field=models.IntegerField(help_text='记忆等级', unique=True),
        ),
    ]
