# Generated by Django 2.2 on 2019-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_databases', '0009_auto_20190416_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishwordrecordmodel',
            name='memory_power',
        ),
        migrations.RemoveField(
            model_name='englishwordrecordmodel',
            name='previous_memory_time',
        ),
        migrations.AddField(
            model_name='englishwordrecordmodel',
            name='level',
            field=models.IntegerField(default=0, help_text='单词级别'),
        ),
    ]
