# Generated by Django 2.2 on 2019-04-20 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_databases', '0011_auto_20190416_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_time', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField()),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
