# Generated by Django 2.2 on 2019-04-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiveFileModel',
        ),
    ]
