# Generated by Django 2.2 on 2019-04-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_receivefilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiveFileModel',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pet_name',
        ),
    ]
